services:
  db:
    image: postgres:17.4
    container_name: meal-plan-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meal-plan-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      start_interval: 10s
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
